---
- id: check-zero-width-spaces
  name: Check zero width spaces
  description: Forbid files which have one or more zero width spaces (U+200B).
  entry: hooks/check-zero-width-spaces.sh
  language: script
  types: [file]

- id: hadolint
  name: Hadolint
  description: Run Hadolint on Dockerfiles.
  entry: hooks/hadolint.sh
  language: script
  types: [file, dockerfile]

- id: packer-validate
  name: Packer Validate
  description: Run 'packer validate' on JSON files.
  entry: hooks/packer-validate.sh
  language: script
  files: \.json$
  types: [file, json]

- id: terraform-unused-variables
  name: Check unused Terraform variables
  description: Forbid unused Terraform variables.
  entry: hooks/terraform-unused-variables.sh
  language: script
  files: (vars|variables)\.tf$
  types: [text]
