---
- id: packer-validate
  name: Packer Validate
  description: Run 'packer validate' on Packer template files.
  entry: hooks/packer-validate.sh
  language: script
  files: \.json$
  types: [file, json]

- id: check-zero-width-spaces
  name: Check zero width spaces
  description: Forbid files which have one or more zero width spaces (U+200B).
  entry: hooks/check-zero-width-spaces.sh
  language: script
  types: [text]
