---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: git://github.com/adrienverge/yamllint
    rev: v1.25.0
    hooks:
      - id: yamllint
        entry: yamllint --strict
  - repo: git://github.com/gruntwork-io/pre-commit
    rev: v0.1.11
    hooks:
      - id: shellcheck
