---
- id: packer-validate
  name: Packer Validate
  description: Run 'packer validate' on Packer template files.
  entry: hooks/packer-validate.sh
  language: script
  files: \.json$
  types: [file, json]
