language: python

python:
  - 3.7

install:
  - pip install -U pre-commit

before_script:
  - pre-commit --version

script:
  - pre-commit run --all-files --verbose

notifications:
  email:
    on_success: never
    on_failure: always
