---
name: main

# yamllint disable-line rule:truthy
on: [push]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    container:
      image: flaudisio/pre-commit:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run pre-commit
        run: |
          pre-commit --version
          pre-commit run --all-files --verbose --show-diff-on-failure --color always
